---
title: "Final Report"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(httr)
library(rvest)
library(openintro)
library(ggmap)
library(patchwork)
library(modelr)
library(purrr)
library(flexdashboard)
library(viridis)
library(plotly)
library(stringr)
library(p8105.datasets)
library(kableExtra)
library(shiny)
```

## Team Members and UNIs:

Melanie Mayer; mm4963  
Jaisal Amin; ja3314  
Rebekah Yu; dry2115  
Courtney Johnson; cj2493  
  
## Motivation, Background, and Initial Questions:  

Motivation for this project was rooted in the group's collective interest in the impact of public health initiatives on health outcomes. While exploring for related datasets, we found city-level data on health practices and health outcomes from the CDC. Project objectives and analysis plans were mainly driven by the data and the information available from the data set. 

The initial question we explored was what are the associations between:
  (1) prevalence of lack of health insurance, 
  (2) regular health practices (i.e. pap smear, doctor visits, mammograms), and 
  (3) health outcomes (diabetes, kidney disease, smoking). 
  
To further support our analysis, we hypothesized that health expenditures could be a possible predictor of outcomes and practices, thus, an external data set of health expenditures by state was included. In addition, we were interested in regional trends of health for the data. To obtain regional categories, we found an external data set including four regions and states included in each region. 

## Related WOrk:  

## Initial Questions:  

What are the associations between (1) prevalence of lack of health insurance, (2) regular health practices (i.e. pap smear, doctor visits, mammograms), and (3) health outcomes (diabetes, kidney disease, smoking). We also plan on  creating geographical visualizations of the prevalence of health outcomes by region?

## Data:  
Our data was taken from the 500 cities project. The data used for their analysis was obtained from the Centers of Disease Control, Division of Population Health, Epidemiology, and Surveillance Branch. The dataset provides model-based estimates for the prevalence of various diseases/practices in order to help local public health officials better serve their communities. We filtered out many variables and ultimately chose to only keep diseases associated with higher rates of fatality and/or those that placed a higher burden on our healthcare system. We also kept variables that could be clearly classified as "health practices" or behaviors whose primary purpose is to maintain or improve one's health. Because we were interested in the relationship between these variables and health insurance/expenditure, we kept the variable associated with prevalence of lack of insurance and imported data on healthcare expenditure by state from the Henry J. Kaiser Family Foundation. In order to conduct regional analysis, we imported a dataset that classified states based on region.



## Exploratory Analysis:  

## Additional Analysis:  

## Discussion:  